name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Bun
      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "::add-path::$(bun bin)"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: bun install

      # Step 4: Run TypeScript compilation
      - name: Build project
        run: bun build

      # Step 5: Run tests
      - name: Run tests
        run: bun test
