name: CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      # Step 3: Install dependencies
      - name: Install dependencies
        run: bun install

      # Step 4: Run TypeScript compilation
      - name: Build project
        run: bun run build

      # Step 5: Run tests
      - name: Run tests
        run: bun test
